### ISSUE TITLE
bloomz-7b1-mt模型

### ISSUE THREAD

**Issue by seanychen** [morning-hao/domain-bloom#1]
在第二步，/xxx/bloomz-7b1-mt",  # 这个是重点，下载模型后改成自己的原始模型路径。

如何下载这个原始模型？是bin file吗

**Comment by morning-hao** [comment]
比如这个链接里面的文件，`https://huggingface.co/bigscience/bloomz-7b1-mt/tree/main`，里面有下载的箭头，全部点击下载到一个自己电脑的文件夹下就行，最好所有文件都下载，bin是参数，其他的配置文件也会影响结果，缺少可能加载直接报错
